# Generated by Django 4.2.5 on 2023-09-05 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
